spring:
  profiles:
    active: @profileActive@
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: boot-demo
mybatis:
  mapper-locations: mybatis/**/*Mapper.xml
  #开启多个别名
  type-aliases-package: com.example.boot.model;com.example.boot.openResult
  configuration:                                          # dev中配置打印sql
    cache-enabled: true                                   #开启二级缓存
    map-underscore-to-camel-case: false                   #不开启驼峰自动映射,遵循php版本继续使用下划线
server:
  port: 9000
  tomcat:
    max-threads: 500
logging:
  config: classpath:config/@profileActive@/logback-spring.xml

