CREATE TABLE `customer` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sn` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '客户编号',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户名称',
  `unique_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '唯一识别(店铺id)',
  `customer_category_id` bigint(20) DEFAULT NULL COMMENT '客户属性 一级',
  `customer_category_id2` int(11) DEFAULT NULL COMMENT '客户属性 二级',
  `customer_category_id3` int(11) DEFAULT NULL COMMENT '客户属性 三级',
  `customer_level_id` int(11) DEFAULT NULL COMMENT '淘宝客户等级',
  `shop_url` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '店铺网址',
  `province_id` int(11) DEFAULT NULL COMMENT '省id',
  `city_id` bigint(20) DEFAULT NULL COMMENT '城市id',
  `process_user_id` int(11) DEFAULT NULL COMMENT '跟进人',
  `customer_product_category_id` int(11) DEFAULT NULL COMMENT '主营产品类目',
  `customer_product_nation_id` int(11) DEFAULT NULL COMMENT '主营产品国籍',
  `trade_month` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '客户规模(月度生意量,万元)',
  `customer_gradation` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客户分层 S T Y C',
  `trade_type` tinyint(1) DEFAULT NULL COMMENT '贸易类型 1-跨境 2-一般贸易 3-跨境加一般贸易',
  `activeness` tinyint(1) DEFAULT '0' COMMENT '0-新客户 1-活跃 2-不活跃 3-休眠',
  `total_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '总销售额',
  `created_at` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `deleted_at` timestamp NULL DEFAULT NULL COMMENT '删除时间',
  `delete_status` tinyint(1) DEFAULT '0' COMMENT '删除状态 0-未删除 1-已删除',
  PRIMARY KEY (`id`),
  KEY `customer_name_index` (`name`),
  KEY `customer_shop_url_index` (`shop_url`),
  KEY `customer_category_id` (`customer_category_id`),
  KEY `city_id` (`city_id`),
  KEY `province_id` (`province_id`),
  KEY `customer_level_id` (`customer_level_id`),
  KEY `customer_product_category_id` (`customer_product_category_id`),
  KEY `customer_product_nation_id` (`customer_product_nation_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1296 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户表';

